name: Build EXE with PyInstaller

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  MAIN_SCRIPT: example/3-exporter.py

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt ( pip install -r requirements.txt )

      - name: Package EXE
        run: |
          echo "📦 正在打包 ${{ env.MAIN_SCRIPT }}..."
          pyinstaller --noconsole --onefile ${{ env.MAIN_SCRIPT }}

      - name: Show output files
        run: dir dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: memotrace-exe
          path: dist/${{ env.MAIN_SCRIPT##*/ }.py=.exe}
